### ISSUE TITLE
Inputting name of user causes crash.

### ISSUE THREAD

**Issue by garrettsummerfi3ld** [garrettsummerfi3ld/CopyUserFiles#1]
## Expected Behavior

> What behavior was supposed to happen?

Grab name from input

## Actual Behavior

> What behavior *really* happened

Exception occured

```
Exception has occurred: KeyError
'HOME'
  File "D:\Programming\CopyUserFiles\copy_user_files.py", line 70, in getUserName
    homepath = os.path.dirname(os.environ['HOME']) + os.sep + username
  File "D:\Programming\CopyUserFiles\copy_user_files.py", line 146, in app
    username = getUserName()
  File "D:\Programming\CopyUserFiles\copy_user_files.py", line 184, in <module>
    app()
```

## Steps to Reproduce the Problem

1. Run `python copy_user_files.py`
1. Input name 
1. Crash

## Specifications

- Version: 1.0.0
- Platform: Windows

**Comment by garrettsummerfi3ld** [comment]
Bug is temporarily fixed in f9bda60839e4f113733cd8daf9219fdea7ef6c59

Closing for now.

**Comment by garrettsummerfi3ld** [comment]
Bug is not fixed as of ef5ea6810e5be5533355b3bc6e75300ac36ae57f

Reopening issue.

Stack trace:
```python
Traceback (most recent call last):
  File "X:\users\gsummerfield\Git\CopyUserFiles\copy_user_files.py", line 229, in <module>
    app()
  File "X:\users\gsummerfield\Git\CopyUserFiles\copy_user_files.py", line 186, in app
    username = getUserName()
  File "X:\users\gsummerfield\Git\CopyUserFiles\copy_user_files.py", line 86, in getUserName
    username = str(input('Name of user folder: '))
  File "<string>", line 1, in <module>
NameError: name 'gsummerfield' is not defined
```

**Comment by bgoewert** [comment]
Removing the exception definition in getUserName() let the script run and produce an error.

```python
    except:
        logging.exception(str('Something bad just happened, check stacktrace' +
                          ' to see the logs (＃ﾟДﾟ)').encode('UTF-8'))
```

Also using `logging.exception()` instead of `critical()` will output error information to the log.

```
12-06-19 14:21:58 - ERROR - b'Something bad just happened, check stacktrace to see the logs (\xef\xbc\x83\xef\xbe\x9f\xd0\x94\xef\xbe\x9f)'
Traceback (most recent call last):
  File "copy_user_files.py", line 82, in getUserName
    quit()
  File "C:\Users\bgoewert\AppData\Local\Programs\Python\Python37\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
12-06-19 14:21:58 - INFO - User profile selected: bgoewert
```

**Comment by garrettsummerfi3ld** [comment]
Locking thread, fork is no longer active.

Please consider discussing at the most up to date repo: https://github.com/BGogurt/CopyUserFiles
