### ISSUE TITLE
Unicode characters cause the logger to crash

### ISSUE THREAD

**Issue by garrettsummerfi3ld** [garrettsummerfi3ld/CopyUserFiles#2]
## Expected Behavior

> What behavior was supposed to happen?

Logging is normal and does not crash

## Actual Behavior

> What behavior *really* happened

Logging fails and crashes while handling an exception. **The script however still runs perfectly fine, even with logging failing.**

Stack trace of crash:

```python
Traceback (most recent call last):
  File "logging\__init__.py", line 1037, in emit
  File "c:\program files\python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 119-122: character maps to <undefined>
Call stack:
  File "copy_user_files.py", line 230, in <module>
  File "copy_user_files.py", line 187, in app
  File "copy_user_files.py", line 103, in getUserName
  File "logging\__init__.py", line 1969, in exception
  File "logging\__init__.py", line 1961, in error
  File "logging\__init__.py", line 1412, in error
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "logging\__init__.py", line 1132, in emit
  File "logging\__init__.py", line 1040, in emit
Message: 'Something really bad happened trying to get a username , check stacktrace to see the logs (＃ﾟДﾟ)'
Arguments: ()
```

Stack trace of log file:
```
10-06-19 17:15:48 - INFO - ****************************************************
10-06-19 17:15:48 - INFO - SCRIPT STARTED
10-06-19 17:15:48 - INFO - ****************************************************
10-06-19 17:15:48 - INFO - Attempting to retrieve username...
10-06-19 17:15:48 - INFO - (Namespace(destination=None, username=None), [])
10-06-19 17:15:48 - INFO - Prompting for user name...
10-06-19 17:15:55 - INFO - User profile selected: {username}
10-06-19 17:34:20 - INFO - User destination directory selected: {directory of script}
{Script copies everything like normal)
```
## Steps to Reproduce the Problem

1. Run script (not by building the executable)
2. Input folder
3. Logging crash 

## Specifications

- Version: 1.2.0
- Platform: Windows

**Comment by garrettsummerfi3ld** [comment]
Locking thread, fork is no longer active.

Please consider discussing at the most up to date repo: https://github.com/BGogurt/CopyUserFiles
